### PR TITLE
Support TLS

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Taiga User Story**
504

**Taiga Task(s)**
N/A

**What did you change?**
Added support for passing a TLS key, cert and passphrase into Node.js
Server will still support plain HTTP.
~~When HTTPS is enabled HTTP connections will automatically be forwarded.~~

NOTE: tls is optional, it does not need to be set.
NOTE: when TLS is set passphrase is optional, key and cert are required

**How can we test?**
Add a TLS section to the `config.json`

Example config
``` json
{
  "environment": "development",
  "dashboard": {
    "hostname": "localhost",
    "port": 3000
  },
  "api": {
    "hostname": "localhost",
    "port": 3001
  },
  "database": {
    "hostname": "localhost",
    "name": "prp_development",
    "username": "tester",
    "password": "test",
    "dialect": "mysql",
    "salt": "something secure here"
  },
  "tls": {
    "passphrase": "test",
    "key": "/absolute/path/to/key.pem",
    "cert": "/absolute/path/to/cert.pem"
  }
}
```

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
resolves #295

**Comment by ChristianMurphy** [comment]
Another Note:
If certificates are stored in `/etc/ssl` or another secure, permission locked down area.
Server needs to be started as a super user.

**Comment by poojaRal** [comment]
LGTM

**Comment by iamaureen** [comment]
:shipit:

**Pull request merged**
