### PR TITLE
ESLint 2 RC 0

### PR DESCRIPTION
**Pull request by ChristianMurphy**
More new lint rules, yay :smile:

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@poojaRal this PR makes some changes to the API code could you take a look at that and see if it looks okay?

**Comment by poojaRal** [comment]
It looks okay to me but then we will have to test the APIs again.

**Comment by ChristianMurphy** [comment]
@poojaRal ready for a full review

**Comment by poojaRal** [comment]
APIs have been tested successfully with negative scenarios as well.
LGTM

**Comment by ChristianMurphy** [comment]
@promisasu/developer after this change is merged please run `npm install eslint@next` on your local system so that the `npm run lint` task will work properly locally.

**Pull request merged**
