### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Sets up https://LGTM.co as code review validation for Github

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
LGTM

**Comment by ChristianMurphy** [comment]
LGTM

**Comment by ChristianMurphy** [comment]
Any of theses comments
```
LGTM
:+1: 
:shipit: 
```
from a reviewer will allow PR to be merged

**Comment by ChristianMurphy** [comment]
@poojaRal For now I set this to require just one review.
Once we know the Github usernames of more of the incoming contributors, we could maybe increase it to require more reviews.
What do you think? :thought_balloon:

**Comment by poojaRal** [comment]
Sounds good :)

**Comment by ChristianMurphy** [comment]
@poojaRal just as a test could you comment `LGTM` here so I can see if the webhook is working?

**Comment by poojaRal** [comment]
LGTM

**Comment by ChristianMurphy** [comment]
Thanks!

**Pull request merged**
