### PR TITLE
use Pull Approve

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Switching LGTM.co for Pull Approve because:

1. Pull Approve allows rejecting a Pull Request
2. Pull Approve allows author to be ignored in reviews
3. Pull Approve allows groups of reviewers

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
:+1: testing if I can sign off on my own PR

**Comment by poojaRal** [comment]
Lgtm

**Comment by poojaRal** [comment]
+1

**Comment by poojaRal** [comment]
LGTM

**Comment by ChristianMurphy** [comment]
this may need to be merged to master to work

**Pull request merged**
