### PR TITLE
User Story 456

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Creates a Survey Page, for clinicians to view status of any patient's survey.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
image
This is the current UI.
I was thinking that grouping questions so the question text appears only once with a bullet point list of the options could be more clear.
Any thoughts on the UI?

**Comment by poojaRal** [comment]
Yes the question should appear once. And options. Should be shown as bullet points.

**Comment by ChristianMurphy** [comment]
capture

Changed UI to group question options together.
Thoughts on updated appearance?

**Comment by Monosrija** [comment]
it is better this way. But can we highlight the row for patient's answer by green or something?

**Comment by ChristianMurphy** [comment]
capture

how about a light blue highlight? :smile:

**Comment by ChristianMurphy** [comment]
I'm cautious about using red, yellow or green here, because those colors have been used specifically for compliance measures else where in the system.

**Comment by Monosrija** [comment]
Perfect :) LGTM

**Comment by Monosrija** [comment]
LGTM

**Comment by poojaRal** [comment]
LGTM

**Pull request merged**
