### PR TITLE
Merge development to lead6

### PR DESCRIPTION
**Pull request by mohitkm**
Created a new pull request to merge all the commits from "development" branch to the "lead6" branch.

@ChristianMurphy @poojaRal  We need your confirmation on whether the changes in "development" branch were tested and are safe to merge with "lead6" branch.

We plan on having three branches in the end -- "lead6", "scdpromis/master", "epilepsy"

cc @kgary

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
> We plan on having three branches in the end -- "lead6", "scdpromis/master", "epilepsy"

Very cool! :snowflake: 
That will simplify a lot. :+1: 
One question on the branching strategy, if an important fix is made to some of the core/shared functionality that exists on all branches, what will be the strategy for ensure that all versions of the app get that change?

**Comment by mohitkm** [comment]
Well that's a good question!
We thought of while creating this strategy of three branches.

In reality, Dr. Gary wanted the portal code to be such we can have different configurations for the different portals and the code can remain the same. In that way, we would configure the portal according to the environment it is being deployed on.

However, that is not something for the near future. As of now, we don't have any workaround to the "general change/update" problem other than doing the changes to all branches by hand.

Your inputs to it would be valued.

**Comment by kgary** [comment]
To be precise, the "lead6" branch is essentially the terminal release branch going back to the original conception of the portal you folks built in SER515. We won't backport anything on it as it only supports a single clinical trial which is still technically open in IRB but not actively enrolling patients.


I do want the SCDPROMIS version and the epilepsy portal versions to be one codebase, but the epilepsy team basically copied code and lost the lineage. So I want them to "reattach" based on the commit object where they originally grabbed the code from. For now when a defect is found in one there needs to be a code review to determine if the fix needs to be ported to the other branch. In the long run I would like to have one codebase however.


The vision is to have one "platform" with multiple shared apps and some custom apps based on the nature of the trial/clinical intervention. I would like all my trials to be supported on this one codebase. A CM environment will need to be understood so we know what code is what codebase, what is done by a build tool, what is done at deployment time, and what is done at run-time. The students are currently working a different project that deals with these "portalish" issues, and quickly seeing how abstraction and deferred binding (that portal binds via tools built into the platform itself) are neat concepts but potentially messy to maintain in practice.


Not sure when we will get to implement this full vision... hope I hit one of my outstanding grant proposals.


KG

________________________________

**Comment by mohitkm** [comment]
Closing this pull request because "development" in the current state has not been tested on the production environment.

The current branch deployed on lead6.poly.asu.edu is development without the latest commits.

The most recent commit on the "development" branch deployed on lead6.poly.asu.edu is ac8d3bc31c5c411e464a41b896331c506d5215ce  -- Merge pull request #361 from promisasu/development

**Pull request closed without merging**
