### PR TITLE
Create Initial Survey Instance for New Patient

### PR DESCRIPTION
**Pull request by ChristianMurphy**

### CODE REVIEW

**Comment by poojaRal** [comment]
@ChristianMurphy : I was initially facing issues for max-statements to be allowed as 10 whereas mine were 11. I guess this is regarding the number of constants and variables you can declare in a function. As of now I modified one of them to be hard coded and pushed the change. Can you please check and suggest better ways.

**Comment by ChristianMurphy** [comment]
The change you made is fine.
And I prefer that change over modifying the lint configuration.

**Comment by poojaRal** [comment]
Cool.. Then can we sign it off and merge the change to master?

**Comment by ChristianMurphy** [comment]
LGTM

**Pull request merged**
