### PR TITLE
Improve Patient Table Survey Instance Coloring

### PR DESCRIPTION
**Pull request by ChristianMurphy**
adds state to status handlbars helper
change jQuery extend instead to use native Object.create for cloning objects

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Originally this code colored completed survey instances green, and everything else red.
However code was missed in the transition from 'completed' flag to state for survey instances and has been incorrectly coloring survey instances for a while. 
incorrect-coloring

Updated code uses state for determining status and also adds a new coloring scheme.
'completed' is green, 'in progress' and 'pending' are grey, and all the rest are red.
new-colorization

**Comment by poojaRal** [comment]
Is state-to-status called from the .hbs file itself where all rows are passed to the function to decide color accordingly?

**Comment by ChristianMurphy** [comment]
yep, `state-to-status` is a [handlebars helper](http://handlebarsjs.com/#helpers)

**Comment by poojaRal** [comment]
LGTM

**Comment by iamaureen** [comment]
:shipit:

**Pull request merged**
