### PR TITLE
Log Rotation

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Automatically create a new log file each time the server starts.
This means that old logs are still available in the `logs` directory.
And `npm run log` will only show messages from the current run.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@poojaRal @iamaureen please review

**Comment by iamaureen** [comment]
:shipit:

**Comment by ChristianMurphy** [comment]
@snehi23 this should resolve the frustration with old logs showing up

**Comment by poojaRal** [comment]
LGTM

**Pull request merged**
