### PR TITLE
UI Fixes

### PR DESCRIPTION
**Pull request by ChristianMurphy**
* fixes datatables on windows machines
* updates fullcalendar and tether
* removes generate trial report button
* makes trial view patient list flush with the card layout

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
new appearance of patient list in trial view

update-trial-view-patient-list

**Comment by ChristianMurphy** [comment]
Updated pie chart colors

updated-chart-colors

**Comment by poojaRal** [comment]
LGTM

**Comment by iamaureen** [comment]
:shipit:

**Pull request merged**
