### PR TITLE
Lint Promises

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Taiga User Story**
None

**Taiga Task(s)**
TG-633

**What did you change?**
* Added `eslint-plugin-promise`
* Added Promise related rules.
* Resolved code smells.

**How can we test?**
1. `npm install`
2. `npm run lint`
3. No error messages should appear

Run Application against API and ensure check surveys and get survey still work correctly.

### CODE REVIEW

**Comment by poojaRal** [comment]
This impacts API calls. Did we test them?

**Comment by ChristianMurphy** [comment]
I tested using the application.
I was able to find and complete a valid survey.
And I got the appropriate message when pin DNE.

I have not rechecked the inactive patient pin validation.
Or the inactive, completed and expired survey validation yet.

**Comment by iamaureen** [comment]
LGTM

**Comment by poojaRal** [comment]
LGTM

**Pull request merged**
